language: cpp
dist: trusty
os:
  - linux
compiler:  
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: 'deb http://de.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse'
    packages:
      - cmake


before_script:
  - echo "Preparing environment before compilation"
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install ..

after_success:
  - echo "Everything worked well, will publish executables now to production web server"

