language: cpp
sudo: false
dist: trusty
os:
  - linux
compiler:  
  - gcc
  - clang




before_script:
  - echo "Make sure cmake >3.3 is available."
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz
  - tar -xvzf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1/
  - ./configure
  - make 
  - sudo make install
  - update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - echo "Preparing environment before compilation"
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install ..

after_success:
  - echo "Everything worked well, will publish executables now to production web server"

